### ISSUE TITLE
miss writing for the title

### ISSUE THREAD

**Issue by StanLepunK** [willjw3/responsive-sidebar-react-hooks-tutorial#7]
Hello, there is little probleme in your title you write `reposnsive-sidebar-react-hooks-tutorial` instead `responsive-sidebar-react-hooks-tutorial` not really important, but it's a title :)
thx for this tutorial, very clear and interresting.

**Comment by willjw3** [comment]
@StanLepunK Thanks for pointing that out, and thanks for checking out the tutorial.
